# Generated by Django 5.2.6 on 2025-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_remove_user_mobile_remove_user_user_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(blank=True, to="accounts.role"),
        ),
    ]
