# Generated by Django 5.2.6 on 2025-09-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("organizer", "Organizer")],
                default="student",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
