# Generated by Django 5.2.6 on 2025-09-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_roles_userprofile_user_type_delete_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("organizer", "Organizer")],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprofile",
            unique_together={("user", "user_type")},
        ),
    ]
